// Generated by tools/generate_bob_vectors.py from the editable SVG sources.
package com.ansa1r.projectadhd.ui.mascot.animation

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.*
import androidx.compose.ui.graphics.vector.PathParser

internal data class BobVectorShape(val path: Path, val brush: Brush, val alpha: Float = 1f,
    val style: DrawStyle = Fill, val clip: Path? = null)
internal data class BobVectorLayer(val id: String, val pivot: Offset, val shapes: List<BobVectorShape>)

private fun vectorPath(data: String): Path = PathParser().parsePathString(data).toPath()

internal object BobVectorAssets {
    private val body = Brush.linearGradient(0f to Color(0xFFBD3BE4), 0.5f to Color(0xFFB739D8), 1f to Color(0xFFA733C8), start = Offset(129f, 112f), end = Offset(276f, 341f))
    private val hair = Brush.linearGradient(0f to Color(0xFF00AAB9), 0.48f to Color(0xFF00D95B), 1f to Color(0xFF64F400), start = Offset(141f, 128f), end = Offset(298f, 95f))
    private val scarf = Brush.linearGradient(0f to Color(0xFF00A966), 0.4f to Color(0xFF00D052), 1f to Color(0xFF008F5F), start = Offset(114f, 245f), end = Offset(294f, 284f))
    private val tail = Brush.linearGradient(0f to Color(0xFF00D855), 0.65f to Color(0xFF00C961), 1f to Color(0xFF00A765), start = Offset(254f, 255f), end = Offset(339f, 348f))
    private val tailBack = Brush.linearGradient(0f to Color(0xFF006B65), 1f to Color(0xFF00B751), start = Offset(286f, 281f), end = Offset(360f, 322f))
    private val eyeBlue = Brush.linearGradient(0f to Color(0xFF090845), 0.43f to Color(0xFF063784), 0.75f to Color(0xFF007FE4), 1f to Color(0xFF00F7E8), start = Offset(180f, 159f), end = Offset(177f, 233f))
    private val eyeGlow = Brush.radialGradient(0f to Color(0xFF00FFF1), 0.44f to Color(0xFF00C9F7), 1f to Color(0xFF0057C4), center = Offset(179f, 224f), radius = 36f)
    private val eyeBlueRight = Brush.linearGradient(0f to Color(0xFF090845), 0.43f to Color(0xFF063784), 0.75f to Color(0xFF007FE4), 1f to Color(0xFF00F7E8), start = Offset(270f, 157f), end = Offset(270f, 235f))
    private val eyeGlowRight = Brush.radialGradient(0f to Color(0xFF00FFF1), 0.44f to Color(0xFF00C9F7), 1f to Color(0xFF0057C4), center = Offset(270f, 224f), radius = 38f)
    private val EYE_LEFT_OPEN_clip = vectorPath("M177 156 C157 151 143 172 140 194 C136 215 148 232 164 233 C185 236 203 216 207 194 C212 174 199 156 177 156 Z")
    private val EYE_LEFT_HALF_clip = vectorPath("M144 192 Q172 182 207 189 C208 210 190 235 166 233 C148 233 139 216 144 192 Z")
    private val EYE_RIGHT_OPEN_clip = vectorPath("M268.12 154.44 C247.32 149.24 232.76 171.08 229.64 193.96 C225.48 215.8 237.96 233.48 254.6 234.52 C276.44 237.64 295.16 216.84 299.32 193.96 C304.52 173.16 291 154.44 268.12 154.44 Z")
    private val EYE_RIGHT_HALF_clip = vectorPath("M233.8 191.88 Q262.92 181.48 299.32 188.76 C300.36 210.6 281.64 236.6 256.68 234.52 C237.96 234.52 228.6 216.84 233.8 191.88 Z")

    val layers: Map<String, BobVectorLayer> by lazy { listOf(
        BobVectorLayer("BODY_BASE", Offset(214f, 227f), listOf(
            BobVectorShape(vectorPath("M151 121 C170 106 205 98 234 108 C259 110 284 125 297 146 C314 172 310 208 322 232 C325 237 331 242 334 242 C335 248 330 252 322 249 L313 271 C308 281 308 295 298 308 C283 324 263 322 248 316 C237 331 217 326 204 318 C188 333 166 322 154 311 C132 320 112 303 107 284 C99 273 97 258 106 246 C108 238 113 228 117 216 C112 218 109 221 109 217 C116 204 119 195 122 181 C125 156 137 137 151 121 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M149 140 C130 173 126 203 118 226 C113 238 107 244 108 252 C115 260 130 257 136 250 C129 244 128 232 129 218 C132 188 133 170 149 140 Z"), SolidColor(Color(0xFF8C29B9)), alpha = 0.42f, clip = null),
            BobVectorShape(vectorPath("M203 111 C229 109 264 120 282 142 C299 164 295 188 304 211 C307 223 312 232 317 237 C314 244 306 248 301 248 C304 218 291 198 292 179 C289 141 250 124 203 111 Z"), SolidColor(Color(0xFFDF59ED)), alpha = 0.24f, clip = null),
            BobVectorShape(vectorPath("M115 265 C147 275 174 285 199 286 C231 283 255 282 287 285 L306 288 C303 304 293 314 278 315 C261 300 242 304 224 297 C205 287 188 310 170 303 C148 291 138 301 124 292 Z"), SolidColor(Color(0xFF7D239F)), alpha = 0.58f, clip = null),
            BobVectorShape(vectorPath("M164 136 C175 121 192 117 206 117 C183 130 177 144 167 148 L171 137 Z"), SolidColor(Color(0xFFDA52E8)), alpha = 0.28f, clip = null),
            BobVectorShape(vectorPath("M286 192 C292 205 296 225 290 232 L283 225 Z"), SolidColor(Color(0xFFD64BE7)), alpha = 0.2f, clip = null)
        )),
        BobVectorLayer("BOTTOM_1", Offset(123f, 284f), listOf(
            BobVectorShape(vectorPath("M112 274 C101 279 99 294 104 308 C107 325 118 338 130 337 C143 338 151 327 151 316 C151 298 133 281 126 277 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M105 305 C111 320 119 328 129 328 C137 328 144 324 147 318 C145 332 137 337 129 337 C115 337 108 326 105 305 Z"), SolidColor(Color(0xFFCB49E4)), alpha = 0.55f, clip = null)
        )),
        BobVectorLayer("BOTTOM_2", Offset(164f, 292f), listOf(
            BobVectorShape(vectorPath("M142 283 C136 291 135 307 141 321 C147 336 164 340 180 343 C195 346 204 339 204 327 C202 312 184 300 174 290 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M142 318 C155 334 172 333 184 335 C193 337 199 333 203 328 C204 338 197 344 187 344 C168 341 152 340 142 325 Z"), SolidColor(Color(0xFFCB49E4)), alpha = 0.55f, clip = null)
        )),
        BobVectorLayer("BOTTOM_3", Offset(215f, 300f), listOf(
            BobVectorShape(vectorPath("M190 297 C187 308 191 321 204 328 C218 335 227 348 242 346 C256 345 268 334 265 322 C260 309 240 300 223 297 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M206 326 C221 327 228 340 241 338 C249 337 259 333 264 325 C269 337 251 349 240 346 C227 346 218 336 206 326 Z"), SolidColor(Color(0xFFCB49E4)), alpha = 0.55f, clip = null)
        )),
        BobVectorLayer("BOTTOM_4", Offset(267f, 297f), listOf(
            BobVectorShape(vectorPath("M245 291 C241 299 242 312 251 323 C262 336 282 341 297 336 C309 332 312 322 306 311 C297 299 279 292 267 289 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M255 322 C267 329 283 334 297 329 C302 327 307 322 307 318 C313 329 305 337 293 338 C277 341 263 333 255 322 Z"), SolidColor(Color(0xFFCB49E4)), alpha = 0.55f, clip = null)
        )),
        BobVectorLayer("ARM_LEFT", Offset(114f, 276f), listOf(
            BobVectorShape(vectorPath("M112 261 C105 260 97 266 92 277 C86 289 87 303 94 307 C101 311 112 301 118 295 C125 289 126 281 121 271 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M110 265 C101 268 93 280 93 291 C94 299 98 301 103 298 C100 289 111 280 116 277 Z"), SolidColor(Color(0xFF9024B8)), alpha = 0.62f, clip = null),
            BobVectorShape(vectorPath("M95 287 C89 298 92 305 97 306 L105 302 C99 303 94 299 95 287 Z"), SolidColor(Color(0xFFDC56E9)), alpha = 0.45f, clip = null)
        )),
        BobVectorLayer("ARM_RIGHT", Offset(310f, 244f), listOf(
            BobVectorShape(vectorPath("M304 227 C313 229 324 233 330 240 C335 245 339 250 335 255 C331 260 323 254 316 251 L305 246 Z"), body, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M315 235 C322 243 328 250 335 252 C335 257 330 258 323 253 L313 247 Z"), SolidColor(Color(0xFF8F27B5)), alpha = 0.45f, clip = null)
        )),
        BobVectorLayer("HAIR", Offset(221f, 115f), listOf(
            BobVectorShape(vectorPath("M143 135 C139 140 136 137 139 131 C149 111 169 92 193 86 C208 82 221 82 231 77 C239 73 251 68 263 69 C278 66 289 70 284 78 C280 84 267 84 259 90 C253 94 268 95 277 102 C287 109 301 119 299 126 C298 131 285 121 276 122 C284 127 297 132 303 143 C309 154 316 160 317 169 C317 176 311 171 307 164 C316 187 312 207 321 227 C326 236 330 237 333 241 C334 246 328 247 322 243 C309 235 311 216 306 202 C301 183 302 167 289 151 C284 145 272 140 264 135 C254 131 258 126 269 126 C279 124 257 116 239 113 C222 111 212 114 213 111 C214 108 224 107 231 103 C211 104 191 112 172 126 C160 135 149 148 146 145 C143 143 152 132 157 127 Z"), hair, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M143 132 C155 113 171 100 192 94 C180 107 178 111 166 115 L171 113 C166 121 153 124 143 132 Z"), SolidColor(Color(0xFF048DCB)), alpha = 0.9f, clip = null),
            BobVectorShape(vectorPath("M152 136 C162 126 169 121 178 119 L172 125 C183 117 194 115 204 113 C189 122 174 127 152 142 Z"), SolidColor(Color(0xFF02C88B)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M188 98 C213 82 237 79 254 74 L267 74 C247 81 249 86 234 88 L243 90 C224 91 214 95 202 99 L211 99 C203 103 191 105 181 112 Z"), SolidColor(Color(0xFF00EB38)), alpha = 0.78f, clip = null),
            BobVectorShape(vectorPath("M258 73 C269 69 281 72 280 76 C279 81 263 83 256 85 L263 79 L250 79 Z"), SolidColor(Color(0xFF89F5A8)), alpha = 0.9f, clip = null),
            BobVectorShape(vectorPath("M255 101 C278 101 291 115 296 122 C289 119 281 117 276 118 L283 121 C270 118 267 114 257 113 L263 110 Z"), SolidColor(Color(0xFF91EF00)), alpha = 0.9f, clip = null),
            BobVectorShape(vectorPath("M286 133 C301 142 305 153 309 159 C296 145 294 147 288 141 L296 144 Z"), SolidColor(Color(0xFF9DFF00)), alpha = 0.85f, clip = null),
            BobVectorShape(vectorPath("M161 114 L168 110 L165 115 L159 119 Z"), SolidColor(Color(0xFF9C41CF)), alpha = 0.8f, clip = null)
        )),
        BobVectorLayer("SCARF_NECK", Offset(218f, 258f), listOf(
            BobVectorShape(vectorPath("M114 238 C144 247 174 250 204 252 C243 262 290 263 317 247 C324 249 324 258 317 264 C322 267 319 273 312 276 C282 289 252 284 228 282 C199 282 174 285 154 278 C138 272 128 265 115 262 C107 261 102 253 106 246 C106 241 109 239 114 238 Z"), SolidColor(Color(0xFF006C54)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M113 242 C144 250 174 254 208 256 C242 263 279 269 313 253 C319 251 323 253 318 260 C311 267 295 270 274 271 C295 274 308 270 314 266 C314 273 306 278 284 280 C258 283 239 278 218 277 C194 276 175 282 154 273 C140 267 130 262 116 260 C109 258 105 252 110 247 Z"), scarf, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M127 248 C151 255 175 257 199 258 C208 258 220 263 227 268 C208 267 183 267 161 262 L166 266 C148 263 134 259 125 253 Z"), SolidColor(Color(0xFF00E068)), alpha = 0.7f, clip = null),
            BobVectorShape(vectorPath("M263 266 C283 269 304 264 315 258 C311 267 295 274 274 272 Z"), SolidColor(Color(0xFF00DB51)), alpha = 0.8f, clip = null)
        )),
        BobVectorLayer("SCARF_TAIL", Offset(248f, 258f), listOf(
            BobVectorShape(vectorPath("M267 269 C292 276 302 281 321 280 C345 282 356 275 365 278 C373 278 373 286 367 291 C363 295 353 291 349 291 C358 296 367 298 363 304 C360 311 348 306 342 303 C349 310 359 312 352 318 C346 323 337 317 332 315 C340 323 345 325 340 331 C334 337 326 331 320 328 C327 338 332 339 327 345 C322 350 311 342 302 338 C286 329 275 313 267 294 Z"), tailBack, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M249 252 C263 251 277 266 286 283 C294 298 310 300 329 303 C337 304 338 310 331 313 C325 315 319 311 316 310 C322 316 335 319 331 325 C326 331 314 324 309 320 C314 326 324 334 317 337 C311 341 300 332 296 329 C299 335 292 337 285 332 C273 326 266 311 260 297 C254 282 250 264 237 259 C231 258 240 252 249 252 Z"), SolidColor(Color(0xFF00804D)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M246 254 C259 252 271 265 281 281 C291 298 302 300 328 305 C336 306 334 310 329 311 C322 312 315 307 309 306 C314 313 321 318 327 320 C332 324 327 326 322 325 C313 322 306 316 302 313 C305 321 314 327 315 332 C314 337 305 331 299 326 L288 318 C291 324 296 329 291 331 C282 329 274 319 268 306 C259 287 258 268 245 261 L239 258 Z"), tail, alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M250 257 C263 264 267 281 276 294 C271 281 262 262 256 259 Z"), SolidColor(Color(0xFF36ED67)), alpha = 0.5f, clip = null)
        )),
        BobVectorLayer("BLUSH", Offset(219f, 233f), listOf(
            BobVectorShape(vectorPath("M143 227 C148 224 154 226 152 230 C150 235 139 239 136 235 C133 231 139 228 143 227 Z"), SolidColor(Color(0xFFEE61E7)), alpha = 0.9f, clip = null),
            BobVectorShape(vectorPath("M154 231 C158 226 164 229 163 233 C161 239 154 244 150 241 C146 238 151 233 154 231 Z"), SolidColor(Color(0xFFF77AEB)), alpha = 0.87f, clip = null),
            BobVectorShape(vectorPath("M281 236 C287 231 292 233 290 239 C287 245 278 249 275 245 C273 242 277 239 281 236 Z"), SolidColor(Color(0xFFED66E5)), alpha = 0.9f, clip = null),
            BobVectorShape(vectorPath("M294 237 C300 233 305 238 301 243 C298 247 291 250 289 246 C287 243 291 240 294 237 Z"), SolidColor(Color(0xFFF77AEB)), alpha = 0.85f, clip = null)
        )),
        BobVectorLayer("EYEBROW_LEFT", Offset(220f, 146f), listOf(
            BobVectorShape(vectorPath("M169 148 C175 141 185 139 193 144 C197 147 189 146 185 146 C179 145 174 149 169 149 Z"), SolidColor(Color(0xFF23104A)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYEBROW_RIGHT", Offset(220f, 146f), listOf(
            BobVectorShape(vectorPath("M257 145 C266 143 275 148 280 154 C282 158 276 154 270 151 C265 149 260 149 257 147 Z"), SolidColor(Color(0xFF23104A)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYEBROW_LEFT_BLOCKING", Offset(220f, 146f), listOf(
            BobVectorShape(vectorPath("M165 144 C173 142 184 146 191 154 C194 158 187 153 180 151 C174 149 168 148 165 147 Z"), SolidColor(Color(0xFF23104A)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYEBROW_RIGHT_BLOCKING", Offset(220f, 146f), listOf(
            BobVectorShape(vectorPath("M259 151 C264 143 275 141 283 144 C287 147 280 146 274 147 C268 149 263 152 260 153 Z"), SolidColor(Color(0xFF23104A)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_LEFT_OPEN", Offset(174f, 195f), listOf(
            BobVectorShape(vectorPath("M177 156 C157 151 143 172 140 194 C136 215 148 232 164 233 C185 236 203 216 207 194 C212 174 199 156 177 156 Z"), SolidColor(Color(0xFF13074B)), alpha = 1f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M177 161 C160 157 149 176 146 196 C143 214 153 228 167 228 C185 230 199 211 202 193 C206 176 194 161 177 161 Z"), eyeBlue, alpha = 1f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M151 203 C154 187 170 182 184 190 C198 198 195 222 180 230 C165 237 149 224 151 203 Z"), eyeGlow, alpha = 1f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M151 213 C151 205 150 199 154 193 C154 204 157 212 161 216 L159 222 Z"), SolidColor(Color(0xFF36EAFF)), alpha = 0.8f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M167 217 C174 211 185 215 186 222 C186 230 176 236 169 232 C164 228 163 221 167 217 Z"), SolidColor(Color(0xFF00FFF1)), alpha = 1f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M159 169 C164 162 171 163 170 169 C169 174 163 179 159 179 C153 179 155 173 159 169 Z"), SolidColor(Color(0xFFF7FCFF)), alpha = 1f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M172 221 C175 218 178 220 175 223 L173 225 L176 227 C176 229 170 228 169 225 Z"), SolidColor(Color(0xFFE1FFFF)), alpha = 1f, clip = EYE_LEFT_OPEN_clip),
            BobVectorShape(vectorPath("M192 209 C194 206 197 208 195 211 C193 214 190 213 192 209 Z"), SolidColor(Color(0xFFA9FFFF)), alpha = 0.9f, clip = EYE_LEFT_OPEN_clip)
        )),
        BobVectorLayer("EYE_LEFT_HALF", Offset(174f, 195f), listOf(
            BobVectorShape(vectorPath("M177 156 C157 151 143 172 140 194 C136 215 148 232 164 233 C185 236 203 216 207 194 C212 174 199 156 177 156 Z"), SolidColor(Color(0xFF13074B)), alpha = 1f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M177 161 C160 157 149 176 146 196 C143 214 153 228 167 228 C185 230 199 211 202 193 C206 176 194 161 177 161 Z"), eyeBlue, alpha = 1f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M151 203 C154 187 170 182 184 190 C198 198 195 222 180 230 C165 237 149 224 151 203 Z"), eyeGlow, alpha = 1f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M151 213 C151 205 150 199 154 193 C154 204 157 212 161 216 L159 222 Z"), SolidColor(Color(0xFF36EAFF)), alpha = 0.8f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M167 217 C174 211 185 215 186 222 C186 230 176 236 169 232 C164 228 163 221 167 217 Z"), SolidColor(Color(0xFF00FFF1)), alpha = 1f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M159 169 C164 162 171 163 170 169 C169 174 163 179 159 179 C153 179 155 173 159 169 Z"), SolidColor(Color(0xFFF7FCFF)), alpha = 1f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M172 221 C175 218 178 220 175 223 L173 225 L176 227 C176 229 170 228 169 225 Z"), SolidColor(Color(0xFFE1FFFF)), alpha = 1f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M192 209 C194 206 197 208 195 211 C193 214 190 213 192 209 Z"), SolidColor(Color(0xFFA9FFFF)), alpha = 0.9f, clip = EYE_LEFT_HALF_clip),
            BobVectorShape(vectorPath("M144 192 Q172 182 207 189"), SolidColor(Color(0xFF23104A)), alpha = 1f, style = Stroke(width = 3f, cap = StrokeCap.Round, join = StrokeJoin.Round), clip = null)
        )),
        BobVectorLayer("EYE_LEFT_CLOSED", Offset(174f, 202f), listOf(
            BobVectorShape(vectorPath("M146 198 C159 207 181 212 199 201 C202 199 203 202 200 206 C189 222 162 222 147 207 C142 202 143 196 146 198 Z"), SolidColor(Color(0xFF10104F)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_LEFT_HAPPY", Offset(174f, 193f), listOf(
            BobVectorShape(vectorPath("M143 205 C146 186 158 174 173 177 C185 177 197 187 201 199 C203 205 198 207 194 203 C180 192 167 190 154 207 C149 214 142 213 143 205 Z"), SolidColor(Color(0xFF10104F)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_LEFT_HAPPY_HALF", Offset(174f, 193f), listOf(
            BobVectorShape(vectorPath("M146 201 C158 184 182 182 199 198 C201 202 197 203 194 201 C177 191 161 195 150 205 C147 208 143 204 146 201 Z"), SolidColor(Color(0xFF10104F)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_LEFT_HAPPY_CLOSED", Offset(174f, 198f), listOf(
            BobVectorShape(vectorPath("M147 201 C162 193 180 191 197 199"), SolidColor(Color(0xFF10104F)), alpha = 1f, style = Stroke(width = 4f, cap = StrokeCap.Round, join = StrokeJoin.Round), clip = null)
        )),
        BobVectorLayer("EYE_RIGHT_OPEN", Offset(265f, 195f), listOf(
            BobVectorShape(vectorPath("M268.12 154.44 C247.32 149.24 232.76 171.08 229.64 193.96 C225.48 215.8 237.96 233.48 254.6 234.52 C276.44 237.64 295.16 216.84 299.32 193.96 C304.52 173.16 291 154.44 268.12 154.44 Z"), SolidColor(Color(0xFF13074B)), alpha = 1f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M268.12 159.64 C250.44 155.48 239 175.24 235.88 196.04 C232.76 214.76 243.16 229.32 257.72 229.32 C276.44 231.4 291 211.64 294.12 192.92 C298.28 175.24 285.8 159.64 268.12 159.64 Z"), eyeBlueRight, alpha = 1f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M241.08 203.32 C244.2 186.68 260.84 181.48 275.4 189.8 C289.96 198.12 286.84 223.08 271.24 231.4 C255.64 238.68 239 225.16 241.08 203.32 Z"), eyeGlowRight, alpha = 1f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M241.08 213.72 C241.08 205.4 240.04 199.16 244.2 192.92 C244.2 204.36 247.32 212.68 251.48 216.84 L249.4 223.08 Z"), SolidColor(Color(0xFF36EAFF)), alpha = 0.8f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M257.72 217.88 C265 211.64 276.44 215.8 277.48 223.08 C277.48 231.4 267.08 237.64 259.8 233.48 C254.6 229.32 253.56 222.04 257.72 217.88 Z"), SolidColor(Color(0xFF00FFF1)), alpha = 1f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M249.4 167.96 C254.6 160.68 261.88 161.72 260.84 167.96 C259.8 173.16 253.56 178.36 249.4 178.36 C243.16 178.36 245.24 172.12 249.4 167.96 Z"), SolidColor(Color(0xFFF7FCFF)), alpha = 1f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M262.92 222.04 C266.04 218.92 269.16 221 266.04 224.12 L263.96 226.2 L267.08 228.28 C267.08 230.36 260.84 229.32 259.8 226.2 Z"), SolidColor(Color(0xFFE1FFFF)), alpha = 1f, clip = EYE_RIGHT_OPEN_clip),
            BobVectorShape(vectorPath("M283.72 209.56 C285.8 206.44 288.92 208.52 286.84 211.64 C284.76 214.76 281.64 213.72 283.72 209.56 Z"), SolidColor(Color(0xFFA9FFFF)), alpha = 0.9f, clip = EYE_RIGHT_OPEN_clip)
        )),
        BobVectorLayer("EYE_RIGHT_HALF", Offset(265f, 195f), listOf(
            BobVectorShape(vectorPath("M268.12 154.44 C247.32 149.24 232.76 171.08 229.64 193.96 C225.48 215.8 237.96 233.48 254.6 234.52 C276.44 237.64 295.16 216.84 299.32 193.96 C304.52 173.16 291 154.44 268.12 154.44 Z"), SolidColor(Color(0xFF13074B)), alpha = 1f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M268.12 159.64 C250.44 155.48 239 175.24 235.88 196.04 C232.76 214.76 243.16 229.32 257.72 229.32 C276.44 231.4 291 211.64 294.12 192.92 C298.28 175.24 285.8 159.64 268.12 159.64 Z"), eyeBlueRight, alpha = 1f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M241.08 203.32 C244.2 186.68 260.84 181.48 275.4 189.8 C289.96 198.12 286.84 223.08 271.24 231.4 C255.64 238.68 239 225.16 241.08 203.32 Z"), eyeGlowRight, alpha = 1f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M241.08 213.72 C241.08 205.4 240.04 199.16 244.2 192.92 C244.2 204.36 247.32 212.68 251.48 216.84 L249.4 223.08 Z"), SolidColor(Color(0xFF36EAFF)), alpha = 0.8f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M257.72 217.88 C265 211.64 276.44 215.8 277.48 223.08 C277.48 231.4 267.08 237.64 259.8 233.48 C254.6 229.32 253.56 222.04 257.72 217.88 Z"), SolidColor(Color(0xFF00FFF1)), alpha = 1f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M249.4 167.96 C254.6 160.68 261.88 161.72 260.84 167.96 C259.8 173.16 253.56 178.36 249.4 178.36 C243.16 178.36 245.24 172.12 249.4 167.96 Z"), SolidColor(Color(0xFFF7FCFF)), alpha = 1f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M262.92 222.04 C266.04 218.92 269.16 221 266.04 224.12 L263.96 226.2 L267.08 228.28 C267.08 230.36 260.84 229.32 259.8 226.2 Z"), SolidColor(Color(0xFFE1FFFF)), alpha = 1f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M283.72 209.56 C285.8 206.44 288.92 208.52 286.84 211.64 C284.76 214.76 281.64 213.72 283.72 209.56 Z"), SolidColor(Color(0xFFA9FFFF)), alpha = 0.9f, clip = EYE_RIGHT_HALF_clip),
            BobVectorShape(vectorPath("M233.8 191.88 Q262.92 181.48 299.32 188.76"), SolidColor(Color(0xFF23104A)), alpha = 1f, style = Stroke(width = 3f, cap = StrokeCap.Round, join = StrokeJoin.Round), clip = null)
        )),
        BobVectorLayer("EYE_RIGHT_CLOSED", Offset(265f, 202f), listOf(
            BobVectorShape(vectorPath("M235.88 198.12 C249.4 207.48 272.28 212.68 291 201.24 C294.12 199.16 295.16 202.28 292.04 206.44 C280.6 223.08 252.52 223.08 236.92 207.48 C231.72 202.28 232.76 196.04 235.88 198.12 Z"), SolidColor(Color(0xFF10104F)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_RIGHT_HAPPY", Offset(265f, 193f), listOf(
            BobVectorShape(vectorPath("M232.76 205.4 C235.88 185.64 248.36 173.16 263.96 176.28 C276.44 176.28 288.92 186.68 293.08 199.16 C295.16 205.4 289.96 207.48 285.8 203.32 C271.24 191.88 257.72 189.8 244.2 207.48 C239 214.76 231.72 213.72 232.76 205.4 Z"), SolidColor(Color(0xFF10104F)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_RIGHT_HAPPY_HALF", Offset(265f, 193f), listOf(
            BobVectorShape(vectorPath("M235.88 201.24 C248.36 183.56 273.32 181.48 291 198.12 C293.08 202.28 288.92 203.32 285.8 201.24 C268.12 190.84 251.48 195 240.04 205.4 C236.92 208.52 232.76 204.36 235.88 201.24 Z"), SolidColor(Color(0xFF10104F)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("EYE_RIGHT_HAPPY_CLOSED", Offset(265f, 198f), listOf(
            BobVectorShape(vectorPath("M236.92 201.24 C252.52 192.92 271.24 190.84 288.92 199.16"), SolidColor(Color(0xFF10104F)), alpha = 1f, style = Stroke(width = 4f, cap = StrokeCap.Round, join = StrokeJoin.Round), clip = null)
        )),
        BobVectorLayer("MOUTH_IDLE", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M210 229 C215 239 225 240 231 231"), SolidColor(Color(0xFF210B47)), alpha = 1f, style = Stroke(width = 4f, cap = StrokeCap.Round, join = StrokeJoin.Round), clip = null)
        )),
        BobVectorLayer("MOUTH_SMILE", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M207 227 C217 235 228 236 236 228 C233 243 215 246 207 227 Z"), SolidColor(Color(0xFF140B46)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("MOUTH_SMALL", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M210 228 Q220 231 231 228 C229 244 214 246 210 228 Z"), SolidColor(Color(0xFF100A3E)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M216 236 C219 232 225 235 226 239 C222 244 218 242 216 236 Z"), SolidColor(Color(0xFFED55DF)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("MOUTH_MEDIUM", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M207 226 Q220 229 234 225 C233 241 226 251 219 247 C211 243 209 234 207 226 Z"), SolidColor(Color(0xFF100A3E)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M214 237 C217 232 225 236 228 241 C225 249 217 247 214 237 Z"), SolidColor(Color(0xFFEE55DF)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("MOUTH_WIDE", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M204 223 Q220 226 237 221 C238 238 230 254 220 251 C210 248 206 234 204 223 Z"), SolidColor(Color(0xFF100A3E)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M211 237 C217 230 227 234 231 241 C227 253 216 251 211 237 Z"), SolidColor(Color(0xFFEE55DF)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("MOUTH_BLOCKING_IDLE", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M209 238 C215 228 226 229 232 240"), SolidColor(Color(0xFF210B47)), alpha = 1f, style = Stroke(width = 4f, cap = StrokeCap.Round, join = StrokeJoin.Round), clip = null)
        )),
        BobVectorLayer("MOUTH_BLOCKING_SMALL", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M210 238 C216 228 226 230 232 240 Q221 237 210 238 Z"), SolidColor(Color(0xFF100A3E)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("MOUTH_BLOCKING_MEDIUM", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M208 239 C214 222 229 227 234 242 C228 247 216 245 208 239 Z"), SolidColor(Color(0xFF100A3E)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M215 240 Q224 236 229 243 Q222 247 215 240 Z"), SolidColor(Color(0xFFDB50CF)), alpha = 1f, clip = null)
        )),
        BobVectorLayer("MOUTH_BLOCKING_WIDE", Offset(220f, 236f), listOf(
            BobVectorShape(vectorPath("M206 240 C211 217 232 221 236 244 C228 253 213 249 206 240 Z"), SolidColor(Color(0xFF100A3E)), alpha = 1f, clip = null),
            BobVectorShape(vectorPath("M213 244 Q223 237 231 246 C224 252 217 251 213 244 Z"), SolidColor(Color(0xFFDB50CF)), alpha = 1f, clip = null)
        )),
    ).associateBy { it.id } }
}
