#!/usr/bin/env python3
"""Compile the editable, path-only Bob SVGs to cached Compose paths. No raster input."""
from pathlib import Path
import argparse
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'app/src/main/assets/bob/vector'
TARGET = ROOT / 'app/src/main/kotlin/com/ansa1r/projectadhd/ui/mascot/animation/BobVectorAssets.kt'
NS = '{http://www.w3.org/2000/svg}'

def number(value):
    return f'{float(value):g}f'

def color(value):
    if not re.fullmatch(r'#[0-9a-fA-F]{6}', value):
        raise ValueError(f'Unsupported color: {value}')
    return f'Color(0xFF{value[1:].upper()})'

def path_expr(data):
    if not re.fullmatch(r'[MmLlHhVvCcSsQqTtAaZz0-9.,+\-\s]+', data):
        raise ValueError('Invalid SVG path')
    return 'vectorPath(' + json.dumps(data) + ')'

def compile_assets():
    manifest = json.loads((SOURCE / 'layers.json').read_text())
    if manifest['viewBox'] != [0, 0, 400, 400]:
        raise ValueError('All layers must use the shared 400 x 400 coordinates')
    gradients, clips, parsed = {}, {}, []
    for item in manifest['layers']:
        root = ET.parse(SOURCE / item['file']).getroot()
        if root.get('viewBox') != '0 0 400 400':
            raise ValueError(item['file'])
        for element in root.iter():
            tag = element.tag.removeprefix(NS)
            if tag not in {'svg', 'title', 'defs', 'linearGradient', 'radialGradient', 'stop', 'clipPath', 'g', 'path'}:
                raise ValueError(f'Non-path or unsupported element {tag} in {item["file"]}')
            if element.get('transform'):
                raise ValueError('Bake source transforms into the common viewBox before compiling')
            if tag in {'linearGradient', 'radialGradient'}:
                gradients[element.attrib['id']] = element
            if tag == 'clipPath':
                paths = element.findall(NS + 'path')
                if len(paths) != 1:
                    raise ValueError('Use one compound path per clip')
                clips[element.attrib['id']] = paths[0].attrib['d']
        parsed.append((item, root))
    lines = ['// Generated by tools/generate_bob_vectors.py from the editable SVG sources.',
        'package com.ansa1r.projectadhd.ui.mascot.animation', '',
        'import androidx.compose.ui.geometry.Offset',
        'import androidx.compose.ui.graphics.*',
        'import androidx.compose.ui.graphics.drawscope.*',
        'import androidx.compose.ui.graphics.vector.PathParser', '',
        'internal data class BobVectorShape(val path: Path, val brush: Brush, val alpha: Float = 1f,',
        '    val style: DrawStyle = Fill, val clip: Path? = null)',
        'internal data class BobVectorLayer(val id: String, val pivot: Offset, val shapes: List<BobVectorShape>)', '',
        'private fun vectorPath(data: String): Path = PathParser().parsePathString(data).toPath()', '',
        'internal object BobVectorAssets {']
    for name, gradient in gradients.items():
        stops = ', '.join(number(s.get('offset', '0')) + ' to ' + color(s.attrib['stop-color']) for s in gradient)
        if gradient.tag == NS + 'linearGradient':
            a = gradient.attrib
            expr = f'Brush.linearGradient({stops}, start = Offset({number(a["x1"])}, {number(a["y1"])}), end = Offset({number(a["x2"])}, {number(a["y2"])}))'
        else:
            a = gradient.attrib
            expr = f'Brush.radialGradient({stops}, center = Offset({number(a["cx"])}, {number(a["cy"])}), radius = {number(a["r"])})'
        lines.append(f'    private val {name} = {expr}')
    for name, data in clips.items():
        lines.append(f'    private val {name} = {path_expr(data)}')
    def brush(fill):
        return fill[5:-1] if fill.startswith('url(#') else f'SolidColor({color(fill)})'
    count = 0
    lines += ['', '    val layers: Map<String, BobVectorLayer> by lazy { listOf(']
    for item, root in parsed:
        px, py = item['pivot']
        lines.append(f'        BobVectorLayer("{item["id"]}", Offset({number(px)}, {number(py)}), listOf(')
        shapes = []
        def walk(element, opacity=1.0, clip=None):
            nonlocal count
            tag = element.tag.removeprefix(NS)
            if tag in {'defs', 'title'}:
                return
            opacity *= float(element.get('opacity', '1'))
            if element.get('clip-path'):
                clip = element.attrib['clip-path'][5:-1]
                if clip not in clips:
                    raise ValueError(clip)
            if tag == 'path':
                p = path_expr(element.attrib['d'])
                fill = element.get('fill', '#000000')
                if fill != 'none':
                    shapes.append(f'            BobVectorShape({p}, {brush(fill)}, alpha = {number(opacity)}, clip = {clip or "null"})')
                if element.get('stroke'):
                    style = f'Stroke(width = {number(element.get("stroke-width", "1"))}, cap = StrokeCap.Round, join = StrokeJoin.Round)'
                    shapes.append(f'            BobVectorShape({p}, {brush(element.attrib["stroke"])}, alpha = {number(opacity)}, style = {style}, clip = {clip or "null"})')
                count += 1
            for child in element:
                walk(child, opacity, clip)
        walk(root)
        lines.append(',\n'.join(shapes))
        lines.append('        )),')
    lines += ['    ).associateBy { it.id } }', '}','']
    return '\n'.join(lines), parsed, gradients, clips, count

def preview(parsed, gradients, clips):
    root = ET.Element('svg', {'xmlns':'http://www.w3.org/2000/svg','viewBox':'0 0 400 400','width':'400','height':'400'})
    defs = ET.SubElement(root, 'defs')
    def plain(element):
        new = ET.Element(element.tag.removeprefix(NS), element.attrib)
        new.text = element.text
        for child in element:
            new.append(plain(child))
        return new
    for gradient in gradients.values():
        defs.append(plain(gradient))
    for key, data in clips.items():
        ET.SubElement(ET.SubElement(defs, 'clipPath', {'id':key}), 'path', {'d':data})
    chosen = ['BODY_BASE','BOTTOM_1','BOTTOM_2','BOTTOM_3','BOTTOM_4','ARM_LEFT','ARM_RIGHT','HAIR',
        'SCARF_NECK','SCARF_TAIL','EYEBROW_LEFT','EYEBROW_RIGHT','EYE_LEFT_OPEN','EYE_RIGHT_OPEN','BLUSH','MOUTH_IDLE']
    sources = {item['id']:element for item,element in parsed}
    for name in chosen:
        group = sources[name].find(NS+'g')
        root.append(plain(group))
    return ET.tostring(root,encoding='unicode')+'\n'

if __name__ == '__main__':
    args = argparse.ArgumentParser()
    args.add_argument('--check', action='store_true')
    opts = args.parse_args()
    code, parsed, gradients, clips, count = compile_assets()
    if opts.check:
        if not TARGET.exists() or TARGET.read_text() != code:
            raise SystemExit('Generated Compose paths are out of date. Run tools/generate_bob_vectors.py.')
    else:
        TARGET.parent.mkdir(parents=True,exist_ok=True)
        TARGET.write_text(code)
        (ROOT/'docs/bob_vector_preview.svg').write_text(preview(parsed,gradients,clips))
    print(f'{len(parsed)} editable SVGs; {count} source paths; runtime has no bitmap references; generated source is current.')
